import streamlit as st

# ============================================================
# FUNCIÓN PRINCIPAL DE TRADUCCIÓN
# ============================================================
def t(clave: str) -> str:
    """Retorna el texto en el idioma activo del session_state."""
    idioma = st.session_state.get("idioma", "ES")
    return TEXTOS.get(clave, {}).get(idioma, clave)

# ============================================================
# DICCIONARIO COMPLETO DE TRADUCCIONES
# ============================================================
TEXTOS = {

    # ── LOGIN / REGISTRO ──
    "app_titulo":           {"ES": "📈 Academia GMC Trading",          "PT": "📈 Academia GMC Trading"},
    "ingresar":             {"ES": "Ingresar",                         "PT": "Entrar"},
    "registrarse":          {"ES": "Registrarse",                      "PT": "Registrar-se"},
    "recuperar_clave":      {"ES": "Recuperar Clave",                  "PT": "Recuperar Senha"},
    "usuario":              {"ES": "Usuario",                          "PT": "Usuário"},
    "contrasena":           {"ES": "Contraseña",                       "PT": "Senha"},
    "entrar":               {"ES": "Entrar",                           "PT": "Entrar"},
    "cuenta_no_verificada": {"ES": "Cuenta no verificada. Revisa tu email.", "PT": "Conta não verificada. Verifique seu email."},
    "contrasena_incorrecta":{"ES": "Contraseña incorrecta.",           "PT": "Senha incorreta."},
    "usuario_no_encontrado":{"ES": "Usuario no encontrado.",           "PT": "Usuário não encontrado."},
    "bienvenido":           {"ES": "¡Bienvenido!",                     "PT": "Bem-vindo!"},
    "selecciona_idioma":    {"ES": "Idioma / Idioma",                  "PT": "Idioma / Idioma"},
    "idioma_es":            {"ES": "🇻🇪 Español",                      "PT": "🇻🇪 Español"},
    "idioma_pt":            {"ES": "🇧🇷 Português",                    "PT": "🇧🇷 Português"},

    # ── REGISTRO ──
    "nombre_completo":      {"ES": "Nombre completo",                  "PT": "Nome completo"},
    "correo":               {"ES": "Correo electrónico",               "PT": "E-mail"},
    "telefono":             {"ES": "Teléfono",                         "PT": "Telefone"},
    "confirmar_pass":       {"ES": "Confirmar contraseña",             "PT": "Confirmar senha"},
    "pais":                 {"ES": "País",                             "PT": "País"},
    "fecha_cumple":         {"ES": "Fecha de cumpleaños",              "PT": "Data de aniversário"},
    "registrarme":          {"ES": "Registrarme",                      "PT": "Registrar-me"},
    "pass_no_coinciden":    {"ES": "Las contraseñas no coinciden.",    "PT": "As senhas não coincidem."},
    "email_ya_existe":      {"ES": "Ya existe una cuenta con ese correo.", "PT": "Já existe uma conta com esse e-mail."},
    "revisa_correo":        {"ES": "✅ Revisa tu correo para confirmar tu cuenta.", "PT": "✅ Verifique seu e-mail para confirmar sua conta."},
    "codigo_verificacion":  {"ES": "Código de verificación (6 dígitos)", "PT": "Código de verificação (6 dígitos)"},
    "validar_codigo":       {"ES": "Validar código",                   "PT": "Validar código"},
    "cuenta_verificada":    {"ES": "🎉 ¡Cuenta verificada! Ya puedes iniciar sesión.", "PT": "🎉 Conta verificada! Já pode fazer login."},
    "codigo_incorrecto":    {"ES": "Código incorrecto.",               "PT": "Código incorreto."},
    "error_envio_correo":   {"ES": "No se pudo enviar el correo de verificación.", "PT": "Não foi possível enviar o e-mail de verificação."},

    # ── RECUPERAR ──
    "recuperar_titulo":     {"ES": "🔑 Recuperar contraseña",          "PT": "🔑 Recuperar senha"},
    "correo_registrado":    {"ES": "Correo electrónico registrado",    "PT": "E-mail cadastrado"},
    "enviar_codigo":        {"ES": "Enviar código de recuperación",    "PT": "Enviar código de recuperação"},
    "nueva_contrasena":     {"ES": "Nueva contraseña",                 "PT": "Nova senha"},
    "confirmar_nueva":      {"ES": "Confirmar nueva contraseña",       "PT": "Confirmar nova senha"},
    "restablecer":          {"ES": "Restablecer contraseña",           "PT": "Redefinir senha"},
    "pass_actualizada":     {"ES": "✅ Contraseña actualizada. Ya puedes iniciar sesión.", "PT": "✅ Senha atualizada. Já pode fazer login."},
    "correo_no_existe":     {"ES": "No existe un usuario con ese correo.", "PT": "Não existe usuário com esse e-mail."},
    "codigo_enviado":       {"ES": "✅ Código enviado a tu correo.",   "PT": "✅ Código enviado para seu e-mail."},

    # ── NAVEGACIÓN / DASHBOARD ──
    "modulos":              {"ES": "MÓDULOS",                          "PT": "MÓDULOS"},
    "cerrar_sesion":        {"ES": "❌  Cerrar Sesión",                "PT": "❌  Sair"},
    "volver_inicio":        {"ES": "← Volver al inicio",              "PT": "← Voltar ao início"},
    "inicio":               {"ES": "🏠 Inicio",                       "PT": "🏠 Início"},
    "saldo_actual":         {"ES": "Saldo actual",                     "PT": "Saldo atual"},
    "tu_capital":           {"ES": "Tu capital",                       "PT": "Seu capital"},
    "win_rate":             {"ES": "Win Rate",                         "PT": "Win Rate"},
    "ops_cerradas":         {"ES": "ops cerradas",                     "PT": "ops fechadas"},
    "consejo_dia":          {"ES": "💡 Consejo del día",               "PT": "💡 Dica do dia"},

    # ── MÓDULOS — nombres ──
    "mod_metas":            {"ES": "Metas",                            "PT": "Metas"},
    "mod_reporte_metas":    {"ES": "Reporte de Metas",                 "PT": "Relatório de Metas"},
    "mod_bitacora":         {"ES": "Bitácora",                         "PT": "Diário"},
    "mod_cerrar":           {"ES": "Cerrar Operación",                 "PT": "Fechar Operação"},
    "mod_finanzas":         {"ES": "Finanzas",                         "PT": "Finanças"},
    "mod_reportes":         {"ES": "Reportes",                         "PT": "Relatórios"},
    "mod_forum":            {"ES": "Forum",                            "PT": "Fórum"},
    "mod_escuela":          {"ES": "Escuela",                          "PT": "Escola"},
    "mod_backtesting":      {"ES": "Backtesting",                      "PT": "Backtesting"},
    "mod_revision":         {"ES": "Revisión de Operaciones",          "PT": "Revisão de Operações"},
    "mod_membresias":       {"ES": "Membresías",                       "PT": "Assinaturas"},
    "mod_reporte_est":      {"ES": "Reporte de Estudiantes",           "PT": "Relatório de Alunos"},

    # ── MÓDULOS — descripciones ──
    "desc_metas":           {"ES": "Gestiona tus metas de ahorro",     "PT": "Gerencie suas metas de poupança"},
    "desc_reporte_metas":   {"ES": "Visualiza tu progreso financiero", "PT": "Visualize seu progresso financeiro"},
    "desc_bitacora":        {"ES": "Registra nuevas operaciones",      "PT": "Registre novas operações"},
    "desc_cerrar":          {"ES": "Cierra operaciones pendientes",    "PT": "Feche operações pendentes"},
    "desc_finanzas":        {"ES": "Depósitos, retiros y pagos",       "PT": "Depósitos, saques e pagamentos"},
    "desc_reportes":        {"ES": "Análisis de tu rendimiento",       "PT": "Análise do seu desempenho"},
    "desc_forum":           {"ES": "Comunidad de la academia",         "PT": "Comunidade da academia"},
    "desc_escuela":         {"ES": "Material de formación",            "PT": "Material de formação"},
    "desc_backtesting":     {"ES": "Estudia tus estrategias",          "PT": "Estude suas estratégias"},
    "desc_revision":        {"ES": "Revisa las ops de los alumnos",    "PT": "Revise as ops dos alunos"},
    "desc_membresias":      {"ES": "Gestiona accesos y planes",        "PT": "Gerencie acessos e planos"},
    "desc_reporte_est":     {"ES": "Actividad global de alumnos",      "PT": "Atividade global dos alunos"},

    # ── ACCESO DENEGADO ──
    "demo_vencido":         {"ES": "Tu periodo de prueba de 7 días ha terminado.", "PT": "Seu período de teste de 7 dias terminou."},
    "demo_contacto":        {"ES": "Para seguir disfrutando del servicio realiza tu pago.", "PT": "Para continuar usando o serviço, realize seu pagamento."},
    "membresia_vencida":    {"ES": "Tu membresía ha vencido.",         "PT": "Sua assinatura expirou."},
    "cuenta_inactiva":      {"ES": "Tu cuenta está inactiva o suspendida.", "PT": "Sua conta está inativa ou suspensa."},
    "contacto_wp":          {"ES": "📲 Contáctanos por WhatsApp",      "PT": "📲 Entre em contato pelo WhatsApp"},

    # ── BIENVENIDA ──
    "hola":                 {"ES": "Hola",                             "PT": "Olá"},
    "nivel":                {"ES": "Nivel",                            "PT": "Nível"},
    "membresia":            {"ES": "Membresía",                        "PT": "Assinatura"},
    "proximo_vencimiento":  {"ES": "Próximo vencimiento",              "PT": "Próximo vencimento"},

    # ── BITÁCORA ──
    "bitacora_titulo":      {"ES": "📝 Bitácora de Operaciones",       "PT": "📝 Diário de Operações"},
    "nueva_operacion":      {"ES": "🚀 Nueva Operación",               "PT": "🚀 Nova Operação"},
    "instrumento":          {"ES": "Instrumento",                      "PT": "Instrumento"},
    "accion":               {"ES": "Acción",                           "PT": "Ação"},
    "compra":               {"ES": "COMPRA",                           "PT": "COMPRA"},
    "venta":                {"ES": "VENTA",                            "PT": "VENDA"},
    "valor_bala":           {"ES": "Valor de la Bala ($)",             "PT": "Valor da Bala ($)"},
    "ratio_objetivo":       {"ES": "Ratio Objetivo (1:X)",             "PT": "Ratio Objetivo (1:X)"},
    "precio_entrada":       {"ES": "Precio de Entrada",                "PT": "Preço de Entrada"},
    "precio_sl":            {"ES": "Precio de SL",                     "PT": "Preço de SL"},
    "lotaje_sugerido":      {"ES": "📊 Lotaje sugerido",               "PT": "📊 Lote sugerido"},
    "tp_sugerido":          {"ES": "🎯 TP sugerido",                   "PT": "🎯 TP sugerido"},
    "alerta_riesgo":        {"ES": "🚨 **Alerta de riesgo:** Tu bala supera el 10% del saldo.", "PT": "🚨 **Alerta de risco:** Sua bala supera 10% do saldo."},
    "evidencia_visual":     {"ES": "🖼️ Evidencia Visual",             "PT": "🖼️ Evidência Visual"},
    "grafico_mayor":        {"ES": "📈 Gráfico Mayor",                 "PT": "📈 Gráfico Maior"},
    "grafico_menor":        {"ES": "📉 Gráfico Menor",                 "PT": "📉 Gráfico Menor"},
    "grafico_ejecucion":    {"ES": "⚡ Gráfico Ejecución",             "PT": "⚡ Gráfico Execução"},
    "grafico_resultado":    {"ES": "🏁 Gráfico Resultado",             "PT": "🏁 Gráfico Resultado"},
    "estado_emocional":     {"ES": "🧠 Estado Emocional",              "PT": "🧠 Estado Emocional"},
    "observaciones":        {"ES": "📝 Observaciones",                 "PT": "📝 Observações"},
    "guardar_operacion":    {"ES": "💾 Guardar Operación",             "PT": "💾 Salvar Operação"},
    "operacion_guardada":   {"ES": "✅ Operación registrada correctamente.", "PT": "✅ Operação registrada com sucesso."},
    "faltan_datos":         {"ES": "⚠️ Completa los datos técnicos: Entrada, SL y Bala son obligatorios.", "PT": "⚠️ Complete os dados técnicos: Entrada, SL e Bala são obrigatórios."},
    "saldo_actual2":        {"ES": "💵 Saldo actual",                  "PT": "💵 Saldo atual"},
    "sin_deposito":         {"ES": "⚠️ Debes realizar tu primer depósito en **Finanzas** antes de abrir operaciones.", "PT": "⚠️ Faça seu primeiro depósito em **Finanças** antes de abrir operações."},

    # ── CERRAR OPERACIÓN ──
    "cerrar_titulo":        {"ES": "🏁 Cerrar Operación",              "PT": "🏁 Fechar Operação"},
    "filtro_fecha":         {"ES": "Filtro de fecha",                  "PT": "Filtro de data"},
    "un_dia":               {"ES": "Un día",                           "PT": "Um dia"},
    "rango_dias":           {"ES": "Rango de días",                    "PT": "Intervalo de dias"},
    "selecciona_fecha":     {"ES": "Selecciona la fecha",              "PT": "Selecione a data"},
    "fecha_inicial":        {"ES": "Fecha inicial",                    "PT": "Data inicial"},
    "fecha_final":          {"ES": "Fecha final",                      "PT": "Data final"},
    "todos":                {"ES": "Todos",                            "PT": "Todos"},
    "estado_final":         {"ES": "Estado Final",                     "PT": "Estado Final"},
    "monto_final":          {"ES": "Monto Final ($)",                  "PT": "Valor Final ($)"},
    "drawdown":             {"ES": "📉 Drawdown máximo alcanzado",     "PT": "📉 Drawdown máximo atingido"},
    "evidencia_final":      {"ES": "🖼️ Evidencia Final del resultado", "PT": "🖼️ Evidência Final do resultado"},
    "tomar_foto":           {"ES": "📷 Tomar foto",                    "PT": "📷 Tirar foto"},
    "subir_archivo":        {"ES": "📂 Subir archivo",                 "PT": "📂 Enviar arquivo"},
    "obs_finales":          {"ES": "Observaciones finales",            "PT": "Observações finais"},
    "cerrar_btn":           {"ES": "💾 Cerrar Operación",              "PT": "💾 Fechar Operação"},
    "op_cerrada":           {"ES": "✅ Operación cerrada correctamente.", "PT": "✅ Operação fechada com sucesso."},
    "no_pendientes":        {"ES": "✅ No hay operaciones pendientes en el rango seleccionado.", "PT": "✅ Não há operações pendentes no período selecionado."},
    "selecciona_op":        {"ES": "🎯 Selecciona la operación a cerrar:", "PT": "🎯 Selecione a operação a fechar:"},

    # ── FINANZAS ──
    "finanzas_titulo":      {"ES": "💰 Finanzas",                      "PT": "💰 Finanças"},
    "deposito":             {"ES": "➕ Depósito",                      "PT": "➕ Depósito"},
    "retiro":               {"ES": "➖ Retiro",                        "PT": "➖ Saque"},
    "pago_academia":        {"ES": "📑 Pago Academia",                 "PT": "📑 Pagamento Academia"},
    "historial":            {"ES": "📋 Historial",                     "PT": "📋 Histórico"},
    "monto":                {"ES": "Monto ($)",                        "PT": "Valor ($)"},
    "notas":                {"ES": "Notas (opcional)",                 "PT": "Notas (opcional)"},
    "guardar_deposito":     {"ES": "💾 Guardar Depósito",              "PT": "💾 Salvar Depósito"},
    "guardar_retiro":       {"ES": "💾 Guardar Retiro",                "PT": "💾 Salvar Saque"},
    "deposito_ok":          {"ES": "✅ Depósito registrado.",          "PT": "✅ Depósito registrado."},
    "retiro_ok":            {"ES": "✅ Retiro registrado.",            "PT": "✅ Saque registrado."},
    "monto_invalido":       {"ES": "⚠️ Ingresa un monto válido.",      "PT": "⚠️ Insira um valor válido."},
    "fecha_pago":           {"ES": "Fecha del pago",                   "PT": "Data do pagamento"},
    "comprobante":          {"ES": "Comprobante de pago",              "PT": "Comprovante de pagamento"},
    "enviar_revision":      {"ES": "💾 Enviar para revisión",          "PT": "💾 Enviar para revisão"},
    "pago_enviado":         {"ES": "✅ Pago enviado para revisión del administrador.", "PT": "✅ Pagamento enviado para revisão do administrador."},

    # ── METAS ──
    "metas_titulo":         {"ES": "🎯 Metas Financieras",             "PT": "🎯 Metas Financeiras"},
    "mi_meta":              {"ES": "🎯 Mi Meta de Ahorro",             "PT": "🎯 Minha Meta de Poupança"},
    "perfil_financiero":    {"ES": "📋 Perfil Financiero Mensual",     "PT": "📋 Perfil Financeiro Mensal"},
    "diario_gastos":        {"ES": "📒 Diario de Gastos",              "PT": "📒 Diário de Gastos"},
    "nueva_meta":           {"ES": "➕ Registrar nueva meta",          "PT": "➕ Registrar nova meta"},
    "categoria":            {"ES": "Categoría",                        "PT": "Categoria"},
    "descripcion":          {"ES": "Descripción de tu meta",           "PT": "Descrição da sua meta"},
    "capital_objetivo":     {"ES": "Capital objetivo ($)",             "PT": "Capital objetivo ($)"},
    "fecha_limite":         {"ES": "Fecha límite",                     "PT": "Data limite"},
    "guardar_meta":         {"ES": "💾 Guardar Meta",                  "PT": "💾 Salvar Meta"},
    "meta_guardada":        {"ES": "✅ ¡Meta registrada!",             "PT": "✅ Meta registrada!"},
    "meta_cumplida":        {"ES": "🎉 ¡Felicitaciones! ¡Meta cumplida!", "PT": "🎉 Parabéns! Meta alcançada!"},
    "solicitar_orient":     {"ES": "🤝 Solicitar orientación",         "PT": "🤝 Solicitar orientação"},
    "orient_enviada":       {"ES": "✅ Solicitud enviada.",            "PT": "✅ Solicitação enviada."},
    "ahorro":               {"ES": "Ahorro",                           "PT": "Poupança"},
    "inversion":            {"ES": "Inversión",                        "PT": "Investimento"},
    "emergencia":           {"ES": "Emergencia",                       "PT": "Emergência"},
    "ingresos_mes":         {"ES": "💵 Ingresos del mes",              "PT": "💵 Receitas do mês"},
    "gastos_fijos":         {"ES": "💸 Gastos fijos del mes",          "PT": "💸 Gastos fixos do mês"},
    "guardar_perfil":       {"ES": "💾 Guardar Perfil del Mes",        "PT": "💾 Salvar Perfil do Mês"},
    "perfil_guardado":      {"ES": "✅ Perfil guardado.",              "PT": "✅ Perfil salvo."},
    "tipo_movimiento":      {"ES": "Tipo",                             "PT": "Tipo"},
    "gasto":                {"ES": "GASTO",                            "PT": "GASTO"},
    "ingreso":              {"ES": "INGRESO",                          "PT": "RECEITA"},
    "registrar_mov":        {"ES": "💾 Registrar",                     "PT": "💾 Registrar"},

    # ── REPORTES ──
    "reportes_titulo":      {"ES": "📈 Reportes de Rendimiento",       "PT": "📈 Relatórios de Desempenho"},
    "filtros":              {"ES": "🔎 Filtros",                       "PT": "🔎 Filtros"},
    "desde":                {"ES": "Desde",                            "PT": "De"},
    "hasta":                {"ES": "Hasta",                            "PT": "Até"},
    "metricas":             {"ES": "📊 Métricas generales",            "PT": "📊 Métricas gerais"},
    "ganadas":              {"ES": "✅ Ganadas (TP)",                  "PT": "✅ Ganhas (TP)"},
    "perdidas":             {"ES": "❌ Perdidas (SL)",                 "PT": "❌ Perdidas (SL)"},
    "break_even":           {"ES": "➖ Break Even",                    "PT": "➖ Break Even"},
    "total":                {"ES": "📌 Total",                         "PT": "📌 Total"},
    "pnl":                  {"ES": "💰 PNL",                          "PT": "💰 PNL"},
    "exportar":             {"ES": "📤 Exportar Reporte",              "PT": "📤 Exportar Relatório"},
    "generar_pdf":          {"ES": "📄 Generar PDF",                   "PT": "📄 Gerar PDF"},
    "descargar_pdf":        {"ES": "📥 Descargar Reporte PDF",         "PT": "📥 Baixar Relatório PDF"},
    "no_operaciones":       {"ES": "No tienes operaciones registradas aún.", "PT": "Você não tem operações registradas ainda."},

    # ── FORUM ──
    "forum_titulo":         {"ES": "💬 Foro de la Academia",           "PT": "💬 Fórum da Academia"},
    "chat_publico":         {"ES": "🌍 Chat Público",                  "PT": "🌍 Chat Público"},
    "escribe_mensaje":      {"ES": "Escribe un mensaje para todos:",   "PT": "Escreva uma mensagem para todos:"},
    "enviar_publico":       {"ES": "Enviar al chat público",           "PT": "Enviar ao chat público"},
    "msg_enviado":          {"ES": "Mensaje enviado al chat público.", "PT": "Mensagem enviada ao chat público."},
    "mensajes_internos":    {"ES": "📩 Mensajes Internos",             "PT": "📩 Mensagens Internas"},
    "destinatario":         {"ES": "Selecciona destinatario:",         "PT": "Selecione o destinatário:"},
    "msg_privado":          {"ES": "Escribe tu mensaje privado:",      "PT": "Escreva sua mensagem privada:"},
    "enviar_privado":       {"ES": "Enviar mensaje privado",           "PT": "Enviar mensagem privada"},
    "msg_privado_ok":       {"ES": "Mensaje privado enviado.",         "PT": "Mensagem privada enviada."},
    "bandeja_entrada":      {"ES": "📥 Tus mensajes recibidos",        "PT": "📥 Suas mensagens recebidas"},
    "sin_mensajes":         {"ES": "No tienes mensajes privados aún.", "PT": "Você não tem mensagens privadas ainda."},

    # ── BACKTESTING ──
    "bt_titulo":            {"ES": "📊 Backtesting de Estrategias",    "PT": "📊 Backtesting de Estratégias"},
    "nombre_estrategia":    {"ES": "Nombre de la estrategia",          "PT": "Nome da estratégia"},
    "hora_inicial":         {"ES": "Hora inicial (HH:MM:SS)",          "PT": "Hora inicial (HH:MM:SS)"},
    "hora_final":           {"ES": "Hora final (HH:MM:SS)",            "PT": "Hora final (HH:MM:SS)"},
    "confluencias":         {"ES": "Confluencias observadas",          "PT": "Confluências observadas"},
    "resultado":            {"ES": "Resultado",                        "PT": "Resultado"},
    "ratio_esperado":       {"ES": "Ratio esperado",                   "PT": "Ratio esperado"},
    "pnl_unidades":         {"ES": "PNL en unidades",                  "PT": "PNL em unidades"},
    "guardar_estudio":      {"ES": "Guardar estudio",                  "PT": "Salvar estudo"},
    "bt_guardado":          {"ES": "✅ Estudio de backtesting registrado.", "PT": "✅ Estudo de backtesting registrado."},

    # ── REVISIÓN ──
    "revision_titulo":      {"ES": "🔎 Revisión de Operaciones",       "PT": "🔎 Revisão de Operações"},
    "alumno":               {"ES": "Alumno",                           "PT": "Aluno"},
    "fecha_inicio":         {"ES": "Fecha inicio",                     "PT": "Data início"},
    "fecha_fin":            {"ES": "Fecha fin",                        "PT": "Data fim"},
    "ops_encontradas":      {"ES": "📊 Operaciones encontradas",       "PT": "📊 Operações encontradas"},
    "mostrar_evidencias":   {"ES": "Mostrar evidencias gráficas",      "PT": "Mostrar evidências gráficas"},
    "sin_ops":              {"ES": "No se encontraron operaciones con esos filtros.", "PT": "Nenhuma operação encontrada com esses filtros."},

    # ── MEMBRESÍAS ──
    "mem_titulo":           {"ES": "👥 Gestión de Membresías",         "PT": "👥 Gestão de Assinaturas"},
    "lista_usuarios":       {"ES": "📋 Lista de usuarios",             "PT": "📋 Lista de usuários"},
    "gestionar":            {"ES": "⚙️ Gestionar membresía",           "PT": "⚙️ Gerenciar assinatura"},
    "resumen":              {"ES": "📊 Resumen",                       "PT": "📊 Resumo"},
    "selecciona_usuario":   {"ES": "Selecciona el usuario:",           "PT": "Selecione o usuário:"},
    "nuevo_estado":         {"ES": "Nuevo estado:",                    "PT": "Novo estado:"},
    "nuevo_rol":            {"ES": "Nuevo rol:",                       "PT": "Novo papel:"},
    "periodo_acceso":       {"ES": "Período de acceso:",               "PT": "Período de acesso:"},
    "actualizar_mem":       {"ES": "💾 Actualizar Membresía",          "PT": "💾 Atualizar Assinatura"},
    "mem_actualizada":      {"ES": "✅ Membresía actualizada correctamente.", "PT": "✅ Assinatura atualizada com sucesso."},
    "venc_proximos":        {"ES": "⚠️ Vencimientos en los próximos 7 días", "PT": "⚠️ Vencimentos nos próximos 7 dias"},
    "sin_venc":             {"ES": "✅ No hay membresías por vencer en los próximos 7 días.", "PT": "✅ Não há assinaturas vencendo nos próximos 7 dias."},

    # ── ESCUELA ──
    "escuela_titulo":       {"ES": "🎓 Escuela",                       "PT": "🎓 Escola"},
    "sin_material":         {"ES": "No hay material disponible para tu nivel.", "PT": "Não há material disponível para seu nível."},
    "ver_material":         {"ES": "📘 Ver material",                  "PT": "📘 Ver material"},
    "asignar_jerarquia":    {"ES": "⚙️ Asignar jerarquía a estudiantes", "PT": "⚙️ Atribuir hierarquia a alunos"},
    "usuario_estudiante":   {"ES": "Usuario del estudiante",           "PT": "Usuário do aluno"},
    "nuevo_nivel":          {"ES": "Nuevo nivel",                      "PT": "Novo nível"},
    "actualizar_nivel":     {"ES": "Actualizar nivel",                 "PT": "Atualizar nível"},
    "nivel_actualizado":    {"ES": "Nivel actualizado correctamente.", "PT": "Nível atualizado com sucesso."},
    "usuario_no_enc":       {"ES": "Usuario no encontrado.",           "PT": "Usuário não encontrado."},

    # ── REPORTE ESTUDIANTES ──
    "rep_est_titulo":       {"ES": "📊 Reporte Global de Estudiantes", "PT": "📊 Relatório Global de Alunos"},
    "rendimiento_est":      {"ES": "📌 Rendimiento por estudiante",    "PT": "📌 Desempenho por aluno"},
    "ranking":              {"ES": "🏆 Ranking de rendimiento",        "PT": "🏆 Ranking de desempenho"},
    "estadisticas":         {"ES": "📈 Estadísticas globales",         "PT": "📈 Estatísticas globais"},
    "sin_ops_global":       {"ES": "No hay operaciones registradas aún.", "PT": "Não há operações registradas ainda."},

    # ── ERRORES GENERALES ──
    "error_conexion":       {"ES": "No se pudo conectar con Google Sheets.", "PT": "Não foi possível conectar com o Google Sheets."},
    "error_bd":             {"ES": "Base de datos no encontrada.",     "PT": "Banco de dados não encontrado."},
    "error_hoja":           {"ES": "No se encontró la hoja.",          "PT": "Planilha não encontrada."},
    "error_critico":        {"ES": "❌ Error crítico al guardar:",      "PT": "❌ Erro crítico ao salvar:"},
    "sin_permiso":          {"ES": "⚠️ No tienes permisos para acceder a esta sección.", "PT": "⚠️ Você não tem permissão para acessar esta seção."},
}
